{
 "title": "Apps Mobile : Google Play",
 "description": "Acompanhamento das avaliações dos APPs disponíveis na Google Play.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": ".:: MICROSOFT AZURE | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": ".:: MICROSOFT TEAMS | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/Azure.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Azure"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Azure"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Azure"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/Teams.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Teams"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Teams"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Teams"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Azure"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Azure"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Teams"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Teams"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": ".:: MICROSOFT ONE NOTE | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 }
  },
  {
   "title": ".:: MICROSOFT EXCEL | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/OneNote.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :   Microsoft One Note"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação :  Microsoft One Note"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões :  Microsoft One Note"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/Excel.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Excel"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Excel"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Excel"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões :  Microsoft One Note"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação :  Microsoft One Note"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Excel"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Excel"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": ".:: MICROSOFT OFFICE | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 18 }
  },
  {
   "title": ".:: MICROSOFT ONE DRIVE | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 18 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/office.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Office"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Office"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Office"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/oneDrive.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft OneDrive"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft OneDrive"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft OneDrive"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Office"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Office"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft OneDrive"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft OneDrive"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": ".:: MICROSOFT POWER POINT | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 27 }
  },
  {
   "title": ".:: MICROSOFT WORD | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 27 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/powerPoint.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Power Point"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Power Point"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Power Point"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 28 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/word.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Word"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Word"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Word"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Power Point"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Power Point"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Word"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Word"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": ".:: MICROSOFT YAMMER | GOOGLE PLAY ::.",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 36 }
  },
  { "title": ".:: IFOOD | GOOGLE PLAY ::.", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 37 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/Yammer.png\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Versão da Aplicação :  Microsoft Yammer"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Yammer"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Yammer"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 37 },
   "options": {
    "content": "  <center style=\"margin-top: 10px; display: table; vertical-align: center; justify-content: center; align-items: center;\">\n  <img src=\"/public/img/GooglePlay/ifood.png\" style=\"width:65%\"/>\n  </center>\n\n"
   }
  },
  {
   "title": "Versão",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": { "filter": "Versão da Aplicação :  iFood" },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nota App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": { "filter": "Nota da Aplicação : iFood" },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Qtd. Avaliações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : iFood"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : Microsoft Yammer"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Nota da Aplicação : Microsoft Yammer"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": {
      "filter": "Quantidade de Avaliacões : iFood"
     },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Google Play" },
     "host": { "filter": "Google Play" },
     "item": { "filter": "Nota da Aplicação : iFood" },
     "itemTag": { "filter": "Mobile: Google Play" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 1, "x": 11, "y": 45 } }
 ]
}